type Usuario{
        id: Int,
        nome: String,
        email: String,
        telefone: String,
        perfil: Perfil,
}

input usuarioInput{
        nome: String,
        email: String,
        telefone: String
}

input FiltroInput{
    id:Int,
    email: String,
}

type Query{

    usuarios(id: Int): Usuario
    usuario: [Usuario]
}

type Mutation{
    criarUsuario(data: usuarioInput): Usuario!
    atualizarUsuario(data: usuarioInput, id:int):Usuario!
    deletarUsuario(filtro: FiltroInput!) : Boolean;
}